version: 2.1 # use CircleCI 2.1
defaults: &defaults
  environment:
    NODE_ENV: test
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16
    - image: circleci/postgres:11.5
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: circle-test

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    <<: *defaults
    steps: # a collection of executable commands
      - run:
          name: Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  backend-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Install packages
          command: cd ./packages/backend && npm install
      - run:
          name: Run backend tests
          environment:
            DB_USERNAME: root
            TEST_DB_NAME: circle-test
            DB_HOST: localhost
            JWT_SECRET: trakkr-JWT_SECRET
            TEST_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NzMwMzk4NDUsImV4cCI6MTU3MzA0MTY0NX0.1B1ryU93orWpxXM3aK1farIABGEyZ5DiYdoE3ifgL1c
          command: |
            cd ./packages/backend && npm run test && cd ../..
            ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.backend.json packages/backend/coverage/lcov.info
      - persist_to_workspace:
          root: tmp
          paths: codeclimate.backend.json
  
  frontend-tests:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Install packages
          command: cd ./packages/frontend && npm install
      - run:
          name: Run frontend tests
          command: |
            cd ./packages/frontend && npm run test && cd ../..
            ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.frontend.json packages/frontend/coverage/lcov.info
      - persist_to_workspace:
          root: tmp
          paths: codeclimate.frontend.json
  
  upload-coverage:
    <<: *defaults
    environment:
      - CC_TEST_REPORTER_ID: e1fff4931027681693d680f6ce3aebf03095ee61ccd99d60d589fc97e5cea485
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json

workflows:
  version: 2
  commit:
    jobs:
      - build
      - backend-tests:
          requires:
            - build
      - frontend-tests:
          requires:
            - build
      - upload-coverage:
          requires:
            - backend-tests
            - frontend-tests